---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA+c0MutV9pZQ6TLd4XCD6gpIECO3ljl9MaygU3o0c6Xzu19GHAZDg5iQffOZhhgshoJmwPmSIMvcbdByG5ql0aqwETDWlVSqDQInjp4KxmYC1OIDFV4Tm3e0ipkmmrhpw73t5/HXS7cCB2i+esYyHBM/fZzW+oaIruKtIMMMLHqkib3h9rDNC33AjQhnjHHqgl96d5LheZSH7DZY+lRVPJJdxqpEWcV9OH+DrKptKcYqyG5byABFrTdKYvyhwD/s+MuiaxkMOzBpuGV+i+zvrJlSLi82UHMf2jqoJ/TqPbtrjZRC9aVSzIfRiXPcTIQ4YqiUYsUaBSOzPBGJvB3duNnjEmjNdpds6kzpqc5c64kT2E5GRVqi8U4kyY0iK+aem1koR2seKlTGgRDbol83aH142G47kipHPXGjkqZmrK6RhPCrLXhAVc9TDm1qHILyqy6+G3beATVgjveXHguTosQZAvCmgd664RbmqVrC8/ocP3QL3n9hM0wdMIHPzWDDqqup9rZ0hf+8D7P3K1sxA09LkumFgFDi16KcQ3xTJfApKZ5ChiJ04r/MoUZgE2va3WHj8qFltlfbXW/vredNjA/Q9h5oJLt7Lgqo9vmAN7fdrEh/pSEje3zJ8iHW5Jj2neIUyEsPYAhZKPuCoxdRYXDnGrTm6YlTd9wIFFekvMbJdYMyMO3Qup04khX5vKDimGu7LSQLqphMJ7pGMZ1a5fr29xhx2U/grwQZGDH6Vge3cWRXx8zN2z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
