---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA9Fgeucrn8IIXIVH2mXmGCaKZ+g8OmRailfJQ35V9/A35IzCGishDqlK5ufHGSHXfD8ISS9eIdaLfG0dbK1sfnDJwGZ8RaxmLuI9XfN9CTZCY2AJ6xebCCsbysPU3bfEbUS8+twRviRL9qFnxA99lYkWG+nPsMxqMV+HjVwYuhzUFqLQghB07tBOpaEqNljgd6TcbyDVGUPCCC/K7/ZNt9i4Sut9p9MPrgf57dC4BFpO6Vfqh4OUeo6VvEmD5OwmPZNdCoD60ATubJnbv4wIWmU338etGKtVjz4krH7012RhAH92MZJXHUwrCwuBQP1Zhbz5irZk5+5VjqiRj3vhCtEXj2po5VfUFKpF6iWI100BY8T9JPX+GddCr9Dlam+4LrpnrJ0XmsYGccVeGONKxE8BcuZrDXwxS/BA5Q1PafIiPaXJxLflQxyIsWvV6vwAXXaqUYiXoqmwRDDmXoG44dNtl/GwnAepL5HEgmn1Qi5nl8jrP1C0N/HxxHBSdmdvEOrBXBfSK2nZLvaoHsEopP2Ecs7Vlg6Au4xV04kusFn7NWfhkz7WqpL+XeSlXh7+PNkMM7CWb48dg2incHCPm7v0X/iTPN4tB6HhyCsf2FcmhBz/zJlZVuQORnSZv8KjbDkg8h3oep15CdB5T0I9LXSvhCFFgkh9cIC6w3fbS+LcIWFwcWRGJTpwKHeyKJyXuIPO295Ldw0L0DAeJm44Rqt9uexOGHosdxbyd1MPtl78VagmOovU+7
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
