apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  enableSuperuserAccess: true
  instances: 3
  # bootstrap:
  #   initdb:
  #     database: immich
  #     owner: immich
  #     secret: 
  #       name: immich-secret
  #     postInitSQL:
  #     - DROP EXTENSION IF EXISTS vectors
  #     - CREATE EXTENSION vectors
  #     - CREATE EXTENSION cube
  #     - CREATE EXTENSION earthdistance
  storage:
    size: 5Gi