apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage-pve-02.int.prossertech.com
    path: "/data/media/images/"
  mountOptions:
    - nfsvers=4.2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home-03
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
