apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage-pve-02.int.prossertech.com
    path: "/data/media/images/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
