---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.conf.all.src_valid_mark
          value: "1"
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
      containers:
      - name: qbittorrent
        image: hotio/qbittorrent:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 65142
        env:
        - name: VPN_ENABLED
          value: "true"
        - name: VPN_CONF
          value: "wg0"
        - name: VPN_PROVIDER
          value: "generic"
        - name: VPN_LAN_NETWORK
          value: "10.10.0.0/16"
        - name: VPN_EXPOSE_PORTS_ON_LAN
          value: "8080/tcp"
        - name: VPN_AUTO_PORT_FORWARD
          value: "false"
        - name: VPN_KEEP_LOCAL_DNS
          value: "true"
        - name: VPN_FIREWALL_TYPE
          value: "auto"
        - name: VPN_HEALTHCHECK_ENABLED
          value: "true"
        - name: PRIVOXY_ENABLED
          value: "false"
        - name: UNBOUND_ENABLED
          value: "false"
        volumeMounts:
        - name: config 
          mountPath: /config
        - name: data
          mountPath: /data
      volumes:
      - name: config
        nfs:
          server: storage-pve-02.int.prossertech.com
          path: /data/rke/qbittorrent
      - name: data
        nfs:
          server: storage-pve-02.int.prossertech.com
          path: /data/media/torrents
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-http
spec:
  selector:
    app: qbittorrent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-http
  labels:
    name: qbittorrent-http
spec:
  ingressClassName: nginx
  rules:
  - host: qbittorrent.home.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: qbittorrent-http
            port: 
              number: 8080
