apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metube
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/drewjprosser/argo-home.git
    targetRevision: HEAD
    path: apps/metube
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true