apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slskd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: slskd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/slskd
    repoURL: https://github.com/drewjprosser/argo-home.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true