apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: starr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/starr
    repoURL: https://github.com/drewjprosser/argo-home.git
    targetRevision: HEAD
    directory: 
      recurse: true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true