---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials-internal
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA+qLPmI+1Nad4yva0yMdVRt9SAbEjmYl5/xF/nYTz06hOhbrV2f3OVGjp4XOXk0+8rpwmP0Wouaa3nWldryzRwXN3okyEmpokUvGGFcW8ZfEobb6GETRPfQbZHj83JXFLiB4fKhDBXjtncgexqhwHcuc9Qi7OFhiYtTJzEU2lTq+3C3L0oCz02lFPwRIwBkCy2QhaPm1HjxsdARXkspcTUh1izJm56cxB5YEwVKoxMS1kIJ+milUWEcaqSb9XqdpqX89eUb2cHQHQ81FN7yZVFCkrxEAalfnWY+d2KUoYdzfOKa6pSH9KPF7R+JmBsFCvyG07TfMNmjKkQnbSXoGYenhn6JfUzMas4zisbeItpUcU4dyL5DBdkfc7n1zrSeciojCYUzSdOcpn+k0KOgpsTOGql5v6PBo3lCHO/jumvDeDVMrGQwq/6Z+JcGmBeK+HbwpaeVHKiC2kb/juSC98jawI5dH4cVEk2iO7saxfk3k5d6DkLiFGXiFaJUsogxBlCl+e79i15PTKuELJrv9M1aNN+RjK+nTIjzIYKg71xEQYXYhkYwYW3m9S44RGMlP1mO1gKRrQxSKyOZg+AO/bYcZfMZ1zdidOgl8CRvzL0aIOrzNRkloFqHKr14LTH3QVB5e39+IexEDSvXVz2Suy50hDf7w9e95urpaXO79mr9P2VTWns+k8usbKDejWslTvTYRsmRiE/tn5jCCEFaWd56bycVFrYUkfxaxw6Nrg1Mk6OoPgsICVigH2ecf0jEtzZRfy7tWA+xpM12TURA4LNRkoupNCdF4wP3ZdUnBZ5vKKU/C2nnYMK1SW3NusrHiMV6rX/3j4QD9OeFfwpVpjOqv3xOXupmwyDZSCOJ4dyyKKna/xMZ+YU/9zy+9dsCKnBYwo0s98qXXXWDKCombvDIo0tuIv/T2e69kkxQqs70UWZBAXrW8Pb
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials-internal
      namespace: cloudflared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAx2tvYvzQ00+UxQqXvVNQdUQz9Hfv/rGA/eTeOy2xquB05OZTB1ZW65AbFsgZRt0xHwzCRRmrKbQ0MqZSVo/f1AEY0I161/9VBlZWtguzj21nUdYaSLxts67wPbgRFYy5i67MZ/7aQEh+DZxcDXBBhJbcYNo27KD+ocurOIiCI5vHQsUDpRPKzbF5BmBC7Xgw+2MWPElnuCBmKlCwDiV4k8B6ZenV3msfuspwoFpqIaJ0F+r/dELksUAdDXYGLeN4DRn8qE/C2B8Lz+tbMIL5Y+BjehAxgkOV70aiqu87i9tXzEU+uZE5Eum8yGLSAnP8y/ARFhuMW2R+6rw3X4LUHVOSGYRbVjfo/f+oHWEhG9pyfssAaxzixa2/YUVOgk11tF/opfEqT0T6xTF7zVrRlz12Vdpyf6Q0Oq9JdEEiqLqwD2ULQ2t5O9iBl2ALN9pZz6Tk7cayHlR4s9sW7e1gm6F/ro981lLGZcbXhFTOqTxTomL+kd4DqbvFpnBRh9TbIq+LHjargS5udDxREHSGX2Pjq98Zh8YDs94WDm/7xaWFkxvWY0caO6yQ9NR/jVvEA6yG3GJgR2vRLOwrIUPhtLiNUTamaKU6dVRyDsz8EmaIvZp8lmxASX09e7QNdXKzhLNISo26mR9a5XNx036gdB8ViJUlett23B21dfGoJqlM7nIwLpiBhw6nm1N7nvo0jmLivtiaCjVnY+tZDtwyYaCD7mgONmJRj8j6SO/AqXRO43MsHd9uyFRfRzEx19s+MASWLNmjsHnF6IezlvjeUfFGwaa3+J2Zo4CtojNnxIM9sIjqWSbp+mG/LNVBI58ezwUsDjeuv0QqU2Sw10opWz+cj/mKx0XElLV472UW+jaszjGJquS0TuwwF180vrUilR7HfmcdViyFOrUjYyZn3yA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
